$aux_dir = "build";
$tmpdir  = "build";
$out_dir = 'build';

ensure_path( 'TEXINPUTS', './contents//' );
ensure_path( 'TEXINPUTS', './diagrams//' );
ensure_path( 'TEXINPUTS', './ugm-beamer-template/themes//' );
ensure_path( 'TEXINPUTS', './ugm-beamer-template/fonts//' );
ensure_path( 'TEXINPUTS', '../../content/proposal/diagrams//' );